server:
  port: 8090

spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/wms?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fv45kl86
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 1309218780@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: llwfaemygygrfjei # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 1309218780@qq.com # 发送方邮件，配在yml中可方便更改

mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: auto


oss:
  accessKey: 3Vq-bWFAS8RCXxvwORL5GZCGK0qcytGspyWOrbb1
  secretKey: 1807fs0TpmgsJXbxP6ozMiVLz8VKW9W1xqcxLs2k
  bucket: lizekai-blog



